const typingText=document.querySelector('.typing text p')
const input=document.querySelector('.wrapper .input field ')
const time=document.querySelector('.time span b')
const typingText=document.querySelector('.typing text p')
const typingText=document.querySelector('.typing text p')
const typingText=document.querySelector('.typing text p')
const typingText=document.querySelector('.typing text p')